{"currPage": "",
 "company_id": "",
 "s_nm_company": "",
 "s_nm_schoolname": "",
 "s_nm_area": "",
 "s_nm_collection": "",
 "s_nm_sig": "",
 "s_nm_address": "",
 "s_nm_manager": "",
 "s_nm_manager_phone": "",
 "s_nm_installer": "",
 "s_nm_end": "",
 "s_st_created": "",
 "s_ed_created": "",
 "s_st_updatedate": "",
 "s_ed_updatedate": ""
 }
